from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from .models import Symbol


@runtime_checkable
class ConnectorV1(Protocol):
    """Version 1 connector contract between the app and a trading terminal."""

    terminal_id: str

    def terminal_state(self) -> dict[str, Any]: ...
    def account_state(self) -> dict[str, Any]: ...
    def available_symbols(self) -> list[Symbol]: ...
    def market_watch_symbols(self) -> list[Symbol]: ...
    def market_watch_catalog(self) -> dict[str, Any]: ...
    def tick(self, broker_symbol: str) -> dict[str, Any]: ...
    def rates(self, broker_symbol: str, timeframe: str, count: int) -> dict[str, Any]: ...
    def historical_market_data(self, broker_symbol: str, count: int = 1200,
                               timeframe: str = "M15") -> dict[str, Any]: ...
    def sr_raw_time_sample(self, broker_symbol: str, count: int = 2) -> dict[str, Any]: ...
    def orders(self) -> dict[str, Any]: ...
    def positions(self) -> dict[str, Any]: ...
    def history_orders(self, date_from: str, date_to: str) -> dict[str, Any]: ...
    def history_deals(self, date_from: str, date_to: str) -> dict[str, Any]: ...
    def history_order_by_ticket(self, ticket: int) -> dict[str, Any]: ...
    def history_deals_by_position(self, position_ticket: int) -> dict[str, Any]: ...
    def submit_order(self, order: dict[str, Any]) -> dict[str, Any]: ...
    def shutdown(self) -> None: ...


@runtime_checkable
class TradingPort(Protocol):
    """Domain-level capabilities consumed by strategies, independent of MT5."""

    def state(self) -> dict[str, Any]: ...
    def positions(self) -> dict[str, Any]: ...
    def validate_market_symbols(self, requested: list[str]) -> dict[str, Any]: ...
    def strategy_market_data(self, symbol_name: str, count: int = 2400,
                             timeframe: str = "M1") -> dict[str, Any]: ...
    def historical_market_data(self, symbol_name: str, count: int = 1200,
                               timeframe: str = "M15") -> dict[str, Any]: ...
    def sr_raw_time_sample(self, symbol_name: str, count: int = 2) -> dict[str, Any]: ...
    def current_tick(self, symbol_name: str) -> dict[str, Any]: ...
    def economic_calendar(self, symbol_name: str) -> dict[str, Any]: ...
    def risk_volume(self, symbol_name: str, side: str, entry: float, stop: float,
                    risk_cash: float, hard_cap: float = 0.01, *, policy: dict | None = None) -> dict[str, Any]: ...
    def send_demo_strategy_order(self, symbol_name: str, side: str, volume: float,
                                 stop: float, target: float, strategy_id: int,
                                 expected_account_fingerprint: str | None = None,
                                 risk_cash: float | None = None,
                                 correlation_id: str | None = None, risk_policy: dict | None = None) -> dict[str, Any]: ...
    def send_real_strategy_order(self, symbol_name: str, side: str, volume: float,
                                 stop: float, target: float, strategy_id: int,
                                 expected_account_fingerprint: str | None = None,
                                 risk_cash: float | None = None,
                                 correlation_id: str | None = None, risk_policy: dict | None = None) -> dict[str, Any]: ...
    def send_demo_analyst_order(self, symbol_name: str, side: str, volume: float,
                                stop: float, target: float,
                                expected_account_fingerprint: str | None = None,
                                risk_cash: float | None = None, max_spread: float | None = None,
                                min_reward_risk: float | None = None,
                                correlation_id: str | None = None, risk_policy: dict | None = None) -> dict[str, Any]: ...
    def send_real_analyst_order(self, symbol_name: str, side: str, volume: float,
                                stop: float, target: float,
                                expected_account_fingerprint: str | None = None,
                                risk_cash: float | None = None, max_spread: float | None = None,
                                min_reward_risk: float | None = None,
                                correlation_id: str | None = None, risk_policy: dict | None = None) -> dict[str, Any]: ...
    def send_demo_sr_order(self, symbol_name: str, side: str, volume: float,
                           stop: float, target: float,
                           expected_account_fingerprint: str | None = None,
                           risk_cash: float | None = None,
                           max_spread: float | None = None,
                           min_reward_risk: float | None = None,
                           correlation_id: str | None = None,
                           risk_policy: dict | None = None) -> dict[str, Any]: ...
    def arm_order_engine(self, engine: str, mode: str = "DEMO",
                         fingerprint: str | None = None) -> bool: ...
    def disarm_order_engine(self, engine: str) -> None: ...
